### ISSUE TITLE
Possibly redundant comparison 

### ISSUE THREAD

**Issue by DaniilMn** [Luzhnuy/attacker#4]
https://github.com/Luzhnuy/attacker/blob/da3a7c29a6f3b5bc3506bd779abdd7b556b6bd3f/attack.py#L47
Not familliar with php, but if attack.status_code >= 302 it always will be => 200.
Did you meant < if attack.status_code <= 302 and attack.status_code >= 200: >?

**Comment by Luzhnuy** [comment]
Yes, sorry it just a misstake
