### ISSUE TITLE
Треды умирают и их фактическое значение постоянно уменьшается

### ISSUE THREAD

**Issue by mrjerr** [Luzhnuy/attacker#5]
посмотреть реальное кол-во тредов можно так

`ps -T au |grep attack | wc -l`

может добавлять их в список, и в clean все not is_alive() удалять и ставить новые согласно общему количеству?

**Comment by kostyamat** [comment]
Пробивається хіба сільгосп, може список сайтів доповнили б, або змінили?

**Comment by Luzhnuy** [comment]
@kostyamat оновим в найближчих декілька хвилин

**Comment by kostyamat** [comment]
Може варто список з зовнішнього урл брати? тут прикол в чому, мій син іспанцям роздає, я батніки зробив, щоб в два кліка. Але переустанавлювати іспанці не будуть, ліниві трохи.

**Comment by Luzhnuy** [comment]
@kostyamat він з зовнішнього і береться )

**Comment by kostyamat** [comment]
Який бренч буде основним? Мастер чи дев?

**Comment by Luzhnuy** [comment]
Мастер
